### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by brspurri** [two-guys-one-code/TGOCMessagesActivity#7]
When I copy the example activity (`MainActivity`) into my app, the rendering is extremely (unusably) slow, and the console outputs: 

```
I/Choreographer: Skipped 120 frames!  The application may be doing too much work on its main thread.
```
repeatedly. Is there any work that can be moved to a background thread safely in order to make the scrolling smooth?

**Comment by brspurri** [comment]
ah, I figured it out. My avatar file is too large. :-/ Remove that, and it loads/scrolls perfectly. However, this is a flag that says the class `TGOCAvatar` should probably resize the drawable.

**Comment by cardosoedgar** [comment]
Hey @brspurri, glad you found the problem for that! You can send a PR to fix it or else i'll be looking at that in the next few days.
